import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

import BottomNav from "@/components/BottomNav";
import ScreenLayout from "@/components/ScreenLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // VARS

  // FUNCTIONS

  // JSX
  return (
    <html lang="en" className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white antialiased`}
      >
        <ScreenLayout>
          <div className="laptopS:pt-[50px] laptopS:pl-[180px] laptopM:pl-[200px] dark:bg-background pb-[50px]">
            {children}
          </div>
        </ScreenLayout>

        <BottomNav />
      </body>
    </html>
  );
}
